=== eeejdm/adambusina.cz/.astro/collections/settings.schema.json
{
  "$ref": "#/definitions/settings",
  "definitions": {
    "settings": {
      "type": "object",
      "properties": {
        "site_title_part1": {
          "type": "string"
        },
        "site_title_part2": {
          "type": "string"
        },
        "logo_image": {
          "type": "string"
        },
        "homepage_hero_heading": {
          "type": "string"
        },
        "homepage_hero_subheading": {
          "type": "string"
        },
        "homepage_hero_cta_label": {
          "type": "string"
        },
        "homepage_hero_cta_link": {
          "type": "string"
        },
        "homepage_signature_image": {
          "type": "string"
        },
        "header_cta_label": {
          "type": "string"
        },
        "header_cta_link": {
          "type": "string"
        },
        "header_navigation_links": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "label",
              "url"
            ],
            "additionalProperties": false
          }
        },
        "footer_intro_text": {
          "type": "string"
        },
        "footer_navigation_links": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "label",
              "url"
            ],
            "additionalProperties": false
          }
        },
        "copyright_text_base": {
          "type": "string"
        },
        "contact_email": {
          "type": "string",
          "format": "email"
        },
        "phone_number": {
          "type": "string"
        },
        "instagram_username": {
          "type": "string"
        },
        "seo_description": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "site_title_part1",
        "site_title_part2",
        "logo_image",
        "homepage_hero_heading",
        "homepage_hero_subheading",
        "homepage_hero_cta_label",
        "homepage_hero_cta_link",
        "header_cta_label",
        "header_cta_link",
        "header_navigation_links",
        "footer_intro_text",
        "copyright_text_base",
        "contact_email"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== eeejdm/adambusina.cz/src/content/settings/config.json
{
  "site_title_part2": "| Fotograf",
  "header_navigation_links": [
    {
      "label": "Domů",
      "url": "/"
    },
    {
      "label": "Galerie",
      "url": "/galerie"
    },
    {
      "label": "O mně",
      "url": "/omne"
    },
    {
      "label": "Služby",
      "url": "/sluzby"
    },
    {
      "label": "Kontakt",
      "url": "/kontakt"
    }
  ],
  "instagram_username": "adamsroams",
  "footer_intro_text": "## Tady to nemusí končit\n\nDěkuji za návštevu mojí stránky. Pokud máte jakýkoliv dotaz, neváhejte a napište mi. Budu se těšit na vzájemnou spolupráci!",
  "logo_image": "/favicons/cropped-favicon-06-300x300.png",
  "copyright_text_base": "Copyright © 2025 Adam Bušina | Fotograf",
  "homepage_hero_heading": "Zaznamenám & doručím",
  "homepage_hero_cta_label": "Objednejte si mě",
  "footer_navigation_links": [],
  "header_cta_label": "Napište mi",
  "homepage_hero_subheading": "Jako reportážní fotograf se postarám o to, aby vaše akce byla profesionálně zaznamenána, a vy jste se nemuseli o nic starat.",
  "seo_description": "",
  "phone_number": "+420 605 856 680",
  "header_cta_link": "/kontakt",
  "homepage_hero_cta_link": "/kontakt",
  "contact_email": "info@adambusina.cz",
  "site_title_part1": "Adam Bušina"
}
